"use client";

import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  BadgeCheck,
  Ban,
  Banknote,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Brackets,
  Brain,
  Bug,
  Building2,
  Cable,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleUser,
  CircleX,
  Clock,
  Cloud,
  CloudOff,
  CloudUpload,
  Coins,
  Compass,
  Computer,
  Contrast,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FileUp,
  Film,
  FilterX,
  Flame,
  FolderOpen,
  Funnel,
  Gauge,
  Gavel,
  GitBranch,
  Globe,
  Hammer,
  History,
  Hourglass,
  House,
  IdCard,
  Image as ImageIcon,
  Info,
  KeyRound,
  Languages,
  Landmark,
  Laptop,
  LayoutGrid,
  Layers,
  Link,
  Link2,
  ListChecks,
  LoaderCircle,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  MapPin,
  MapPinOff,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Network,
  Package,
  PanelLeft,
  Paperclip,
  Pencil,
  PiggyBank,
  Play,
  Plus,
  Power,
  Puzzle,
  QrCode,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCcw,
  Route,
  Save,
  Scale,
  ScanSearch,
  ScatterChart,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Speech,
  Square,
  SquareTerminal,
  Star,
  Sun,
  Table as TableIcon,
  Tag,
  Telescope,
  Terminal,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TriangleAlert,
  Trophy,
  Unlink,
  Upload,
  User,
  UserCog,
  UserPlus,
  UserRoundX,
  Users,
  UsersRound,
  Volume2,
  Video,
  Wallet,
  Waypoints,
  Wifi,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide-react";

import { cn } from "@/shared/utils/cn";

/**
 * Material Symbols ligature name → lucide component.
 *
 * The app used to ship two icon systems: a 600-call-site ligature font for
 * content and lucide for the nav shell. Keeping both meant an extra font
 * download, a flash-of-icon-names workaround, and icons that didn't match
 * stroke weight side by side. This map lets every existing `name` string keep
 * working while rendering a single lucide set.
 *
 * Names are the *source* Material Symbols vocabulary, so `icon="add"` in a page
 * or a constants file needs no edit. Add an entry rather than reaching for the
 * font when a page needs a new glyph.
 */
const ICON_MAP = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  account_circle: CircleUser,
  account_circle_off: UserRoundX,
  account_tree: Workflow,
  activity: Activity,
  add: Plus,
  add_circle: CirclePlus,
  admin_panel_settings: ShieldCheck,
  alert_triangle: AlertTriangle,
  alt_route: GitBranch,
  api: Cable,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  arrow_upward: ArrowUp,
  attach_file: Paperclip,
  attach_money: DollarSign,
  badge: IdCard,
  bar_chart: ChartColumn,
  block: Ban,
  bolt: Zap,
  build: Wrench,
  brush: Sparkles,
  bug_report: Bug,
  business: Building2,
  campaign: Megaphone,
  cancel: CircleX,
  category: Boxes,
  chat: MessageSquare,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud: Cloud,
  cloud_off: CloudOff,
  cloud_upload: CloudUpload,
  code: Braces,
  computer: Computer,
  content_copy: Copy,
  contrast: Contrast,
  cookie: Cookie,
  data_array: Brackets,
  data_object: Braces,
  data_usage: Gauge,
  dark_mode: Moon,
  delete: Trash2,
  deployed_code: Package,
  deployed_code_off: Package,
  description: FileText,
  dns: Network,
  download: Download,
  edit: Pencil,
  gauge: Gauge,
  error: CircleAlert,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  extension: Puzzle,
  file_upload: FileUp,
  filter_alt: Funnel,
  filter_alt_off: FilterX,
  folder_open: FolderOpen,
  gavel: Gavel,
  graphic_eq: AudioLines,
  group_off: UsersRound,
  help: CircleHelp,
  history: History,
  home: House,
  hourglass_top: Hourglass,
  hub: Waypoints,
  image: ImageIcon,
  image_search: ScanSearch,
  info: Info,
  input: ArrowDownUp,
  key: KeyRound,
  key_off: KeyRound,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  lan: Network,
  language: Languages,
  layers: Layers,
  light_mode: Sun,
  link: Link,
  link_off: Unlink,
  lock: Lock,
  lock_open: LockOpen,
  lock_reset: Lock,
  logout: LogOut,
  mail: Mail,
  map: Map,
  map_off: Map,
  map_pin: MapPin,
  map_pin_off: MapPinOff,
  manage_accounts: UserCog,
  menu: Menu,
  menu_book: BookOpen,
  message: MessageSquare,
  mic: Mic,
  mobile: Smartphone,
  monitor: Monitor,
  monitoring: Activity,
  more_horiz: Ellipsis,
  movie: Film,
  music_note: Music,
  neurology: Brain,
  note: BookOpen,
  open_in_new: ExternalLink,
  output: ArrowUpRight,
  pause_circle: CirclePause,
  payments: CreditCard,
  person: User,
  person_add: UserPlus,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_add: CirclePlus,
  power_settings_new: Power,
  progress_activity: LoaderCircle,
  psychology: Brain,
  qr_code_2: QrCode,
  radio_button_unchecked: Circle,
  receipt_long: Receipt,
  record_voice_over: Speech,
  refresh: RefreshCw,
  remove_circle_outline: CircleMinus,
  restart_alt: RotateCcw,
  restore: History,
  rocket_launch: Rocket,
  route: Route,
  savings: PiggyBank,
  scatter_plot: ScatterChart,
  schedule: Clock,
  science: Sparkles,
  search: Search,
  search_off: SearchX,
  security: Shield,
  send: Send,
  settings: Settings,
  shield: Shield,
  shield_lock: ShieldAlert,
  smart_toy: Bot,
  south: ArrowDown,
  star: Star,
  stop: Square,
  stop_circle: CircleStop,
  style: Layers,
  sync: RefreshCw,
  sync_alt: ArrowLeftRight,
  tab: LayoutGrid,
  table: TableIcon,
  tag: Tag,
  terminal: Terminal,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  translate: Languages,
  travel_explore: Compass,
  troubleshoot: Telescope,
  tune: SlidersHorizontal,
  unfold_more: ChevronsUpDown,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  videocam: Video,
  visibility: Eye,
  visibility_off: EyeOff,
  volume_up: Volume2,
  vpn_key: KeyRound,
  warning: TriangleAlert,
  wifi: Wifi,

  // Aliases used in this codebase's own copy that aren't Material names.
  banknote: Banknote,
  bell: Bell,
  blocks: Blocks,
  bot: Bot,
  chart_pie: ChartPie,
  cpu: Cpu,
  database: Database,
  flame: Flame,
  globe: Globe,
  hammer: Hammer,
  laptop: Laptop,
  panel_left: PanelLeft,
  radio: Radio,
  save: Save,
  scale: Scale,
  square_terminal: SquareTerminal,
  trophy: Trophy,
  users: Users,
  wrench: Wrench,
  link_2: Link2,
  coins: Coins,
};

/** Names that should spin whenever they render — they only mean "in flight". */
const SPINNING = new Set(["progress_activity"]);

/**
 * Render a mapped icon by Material Symbols name.
 *
 * An unmapped name renders nothing rather than a broken glyph or the raw
 * string, which is what the old ligature font did before its font loaded.
 */
function Icon({ name, className, size, spin, ...props }) {
  const Cmp = ICON_MAP[name];
  if (!Cmp) return null;
  const shouldSpin = spin ?? SPINNING.has(name);
  return (
    <Cmp
      aria-hidden
      size={size}
      className={cn("shrink-0", shouldSpin && "animate-spin", className)}
      {...props}
    />
  );
}

export { Icon, ICON_MAP };
